<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath></BaseOutputPath>
    <AssemblyName>MBL.DedicatedServer</AssemblyName>
	<OutputPath>..\..\Build\DedicatedServer</OutputPath>
	<LangVersion>10</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AppdataFiles\ArmorMapping.txt" />
    <None Remove="AppdataFiles\QuestFlagsNames.txt" />
    <None Remove="ServerConfig.ini" />
    <None Update="AppdataFiles\Gamemodes.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AppdataFiles\Landmarks.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AppdataFiles\PropHuntLocations.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="ServerConfig.ini">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\ArmorMapping.json" />
    <EmbeddedResource Include="Resources\QuestFlagsNames.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BOTW.Logging\BOTWM.Logging.csproj" />
    
    <ProjectReference Include="..\BOTWM.Server\BOTWM.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Gamemodes.json" />
    <EmbeddedResource Include="Resources\Gamemodes.json" />
    <None Remove="Resources\Landmarks.json" />
    <EmbeddedResource Include="Resources\Landmarks.json" />
    <None Remove="Resources\PropHuntLocations.json" />
    <EmbeddedResource Include="Resources\PropHuntLocations.json" />
  </ItemGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	</PropertyGroup>

</Project>
